const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawnSync}=require('node:child_process'),{pathToFileURL}=require('node:url');
const {parse}=require('./preview-inputs-integration.test'),{source}=require('./preview-client-text.test');
const {hydrate}=require('./helpers/preview-image-hydration');
async function run(){
 const root=path.resolve(process.env.BOO_NPC_DIALOG_RUNTIME_ROOT||path.join(__dirname,'..')),out=path.resolve(process.env.BOO_CLIENT_TEXT_OUT||'artifacts/ctrl-f12-live-r19/browser');fs.mkdirSync(out,{recursive:true});
 const tipSource=source.replace('text=姓名=', 'tips=姓名=$STM(USERNAME) 血量=$STM(HP) 滑块=$STM(SLIDERV_N0)|text=姓名=');
 const initial=parse(tipSource,{},'996PC'),changed=parse(tipSource,{'STM(USERNAME)':'勇士','STM(LEVEL)':'42'},'996PC');
 await hydrate(initial,true);await hydrate(changed,true);
 const overridden=parse(source,{'STM(SLIDERV_N0)':'77'},'996PC');await hydrate(overridden,true);
 const richSource=source+'\n<Text|text=$STM(SLIDERV_N0)|x=60|y=170|color=250|size=20|simplenum=1|scrollwidth=80|scrollheight=26|scrollway=0|scrolltime=2>\n<Button|text=$STM(SLIDERV_N0)|x=60|y=230|width=160|height=30>';
 const rich=parse(richSource.replace('maxvalue=100|defvalue=25','maxvalue=100000|defvalue=25000'),{},'996PC');await hydrate(rich,true);
 const menuSource=source+'\n<MenuItem|menuid=S0|x=60|y=200|width=240|height=30|itemname=姓名=$STM(USERNAME)#血量=$STM(HP)#滑块=$STM(SLIDERV_N0)|select=姓名=$STM(USERNAME)|itemhei=30>';
 const menu=parse(menuSource,{},'996PC');await hydrate(menu,true);
 const encode=x=>JSON.stringify(x).replace(/</g,'\\u003c'),uri=f=>pathToFileURL(path.join(root,f)).href;
 let html=fs.readFileSync(path.join(root,'media/npc-dialog-visual.html'),'utf8').replaceAll('{{STYLE_URI}}',uri('media/npc-dialog-visual.css')).replaceAll('{{SCRIPT_URI}}',uri('media/npc-dialog-visual.js'));
 const renderer=`<script src="${uri('media/npc-dialog-visual.js')}"></script>`;
 html=html.replace(renderer,()=>`<script>window.messages=[];window.acquireVsCodeApi=()=>({postMessage:m=>{messages.push(m);window.bridge?.(m);}});</script>${renderer}`);
 html=html.replace('</body>',()=>`<script>
 const initial=${encode(initial)},changed=${encode(changed)},overridden=${encode(overridden)},rich=${encode(rich)},wait=()=>new Promise(r=>setTimeout(r,80)),check=(v,m)=>{if(!v)throw Error(m);};let revision=0;
 const canvas=()=>document.getElementById('dialogCanvas'),deliver=(model,preserve=false)=>window.dispatchEvent(new MessageEvent('message',{data:{type:'model',model,previewRevision:++revision,preserveDrafts:preserve}}));
 window.addEventListener('load',async()=>{try{await wait();deliver(initial);await wait();const url=location.href;
 check(canvas().textContent.includes('姓名=预览文字 等级=0 数量=0 金币=0'),'default visible text');
 const showTip=()=>{const w=canvas().querySelector('[data-element-id]');w.dispatchEvent(new MouseEvent('mouseenter',{clientX:350,clientY:250}));return document.querySelector('.dialog-tooltip');};
 let tip=showTip();check(tip.textContent==='姓名=预览文字 血量=0 滑块=25','tooltip slots actually replaced');check(tip.getBoundingClientRect().width>0&&getComputedStyle(tip).visibility!=='hidden','tooltip visible');
 const slider=canvas().querySelector('.slider-hitarea'),r=slider.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width*.75,r.y+r.height/2);
 check(r.width>0&&r.height>0&&hit===slider,'slider visible and hittable');
 check([...slider.closest('[data-element-id]').querySelectorAll('img')].every(n=>n.complete&&n.naturalWidth>0),'hydrated slider layers loaded');
 hit.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,clientX:r.x+r.width*.25,clientY:r.y+r.height/2}));
 window.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,clientX:r.x+r.width*.75,clientY:r.y+r.height/2}));
 check(canvas().textContent.includes('滑块=75'),'text changes before release');
 window.dispatchEvent(new MouseEvent('mouseup',{bubbles:true,clientX:r.x+r.width*.75,clientY:r.y+r.height/2}));
 slider.focus();slider.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));check(canvas().textContent.includes('滑块=0'),'keyboard live text');
 tip=showTip();check(tip.textContent==='姓名=预览文字 血量=0 滑块=0','reopened tooltip uses latest slider state');
 window.bridge=m=>{if(m.type==='previewInput'){check(m.name==='STM(USERNAME)'&&m.value==='勇士','client typed value');queueMicrotask(()=>deliver(changed,true));}};
 const input=[...document.querySelectorAll('[data-preview-name]')].find(n=>n.dataset.previewName==='STM(USERNAME)');check(input,'typed field exists');input.focus();input.value='勇士';input.dispatchEvent(new Event('change',{bubbles:true}));await wait();
 check(document.activeElement===input,'focus preserved');check(canvas().textContent.includes('姓名=勇士 等级=42'),'updated client text');
 tip=showTip();check(tip.textContent==='姓名=勇士 血量=0 滑块=0','typed tooltip updates and retained slider draft');
 const label=canvas().querySelector('.styled-text-preview'),box=label.getBoundingClientRect();check(box.width>0&&getComputedStyle(label).visibility!=='hidden','text pixels have visible geometry');
 const wrapper=label.closest('[data-element-id]'),wr=wrapper.getBoundingClientRect();check(wr.right>=box.right-1,'text not clipped by hit wrapper');
 deliver(overridden);await wait();let control=canvas().querySelector('.slider-hitarea');control.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));check(canvas().textContent.includes('滑块=77'),'explicit input overrides slider display');
 deliver(initial);await wait();check(canvas().textContent.includes('滑块=25'),'reset restores automatic binding');
 deliver(rich);await wait();const scroll=canvas().querySelector('.text-scroll-preview');check(scroll.textContent.includes('2.50万')||scroll.textContent.includes('2.5万'),'simplified initial slot');check(Math.abs(scroll.getBoundingClientRect().width-80)<2,'fixed scrolling viewport');
 const styled=scroll.querySelector('.styled-text-preview');check(getComputedStyle(styled).fontSize==='20px'&&getComputedStyle(styled).color!=='','font/color retained');
 control=canvas().querySelector('.slider-hitarea');control.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));check(scroll.textContent.includes('10万'),'simplified live slot');check(canvas().querySelector('.button-caption').textContent==='100000','button caption live slot');check(Math.abs(scroll.getBoundingClientRect().width-80)<2,'live text does not enlarge fixed scroll');
 deliver(changed);await wait();
 const menuModel=${encode(menu)};deliver(menuModel);await wait();
 check(canvas().querySelector('.menu-selected-value').textContent==='姓名=预览文字','menu selected display resolved');
 const openMenu=()=>{const t=canvas().querySelector('.menu-toggle-hitarea'),b=t.getBoundingClientRect(),h=document.elementFromPoint(b.right-8,b.top+b.height/2);check(h===t,'menu toggle hittable');h.click();};
 openMenu();let options=[...canvas().querySelectorAll('.menu-option')];check(options.map(n=>n.textContent).join('/')==='姓名=预览文字/血量=0/滑块=25','expanded menu display');
 options[2].dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
 check(canvas().querySelector('.menu-selected-value').textContent==='滑块=25','keyboard selects display item');
 control=canvas().querySelector('.slider-hitarea');control.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));
 check(canvas().querySelector('.menu-selected-value').textContent==='滑块=100','selected menu live slider');
 openMenu();options=[...canvas().querySelectorAll('.menu-option')];check(options[2].textContent==='滑块=100','reopened option live slider');
 const ob=options[1].getBoundingClientRect(),oh=document.elementFromPoint(ob.left+12,ob.top+ob.height/2);check(options[1].contains(oh),'menu option hittable');oh.click();
 check(canvas().querySelector('.menu-selected-value').textContent==='血量=0','pointer selects display item');
 check(canvas().querySelector('.menu-preview').dataset.menuSelected==='血量=$STM(HP)','selection identity stays source-owned');
 deliver(changed);await wait();
 tip=showTip();check(tip.textContent.includes('姓名=勇士 血量=0'),'final readable tooltip');
 check(location.href===url&&!messages.some(m=>['apply','save','previewNavigate'].includes(m.type)),'display does not write or navigate');
 deliver(menuModel);await wait();openMenu();
 check(canvas().querySelectorAll('.menu-option').length===3,'final readable menu');
 const inspector=document.querySelector('.inspector-pane'),details=document.getElementById('canvasDiagnosticsToggle');
 check(!document.body.classList.contains('inspector-collapsed')&&getComputedStyle(inspector).display!=='none','selected menu restores the Inspector');
 details.click();await wait();
 check(document.body.classList.contains('show-diagnostics'),'Details reveals Inspector diagnostics');
 const param=[...document.querySelectorAll('.parameter-row')].find(n=>n.querySelector('strong')?.textContent.startsWith('itemname'));
 const parameterNameWidth=param?.querySelector('strong').getBoundingClientRect().width||0;
 check(param&&getComputedStyle(param).display==='grid'&&parameterNameWidth>100,'long menu parameter must not crush its name column');
 document.body.dataset.clientText='PASS';
 }catch(e){document.body.dataset.clientText='FAIL';document.body.dataset.error=String(e.stack||e);}});
 </script></body>`);
 const file=path.join(out,'fixture.html');fs.writeFileSync(file,html);const attempts=[];
 const candidates=[...new Set([process.env.BOO_BROWSER_EXECUTABLE,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].filter(p=>p&&fs.existsSync(p)))];assert.ok(candidates.length,'Chromium required');
 for(const [i,executable]of candidates.entries()){
  const r=spawnSync(executable,['--headless=new','--disable-gpu','--no-first-run','--allow-file-access-from-files','--window-size=1440,1000','--virtual-time-budget=4000','--dump-dom','--user-data-dir='+path.join(out,'profile-'+i),'--screenshot='+path.join(out,'preview.png'),pathToFileURL(file).href],{encoding:'utf8',windowsHide:true,timeout:30000,maxBuffer:16*1024*1024});
  const dom=r.stdout||'',version=spawnSync('powershell.exe',['-NoProfile','-Command',`(Get-Item -LiteralPath '${executable.replace(/'/g,"''")}').VersionInfo.ProductVersion`],{encoding:'utf8',windowsHide:true}).stdout.trim();
  attempts.push({executable,version,status:r.status,error:String(r.error||''),diagnostic:dom.match(/data-error="[^"]*"/)?.[0]});fs.writeFileSync(path.join(out,'attempts.json'),JSON.stringify(attempts,null,2));fs.writeFileSync(path.join(out,'dom-'+i+'.html'),dom);
  if(r.status===0&&dom.includes('data-client-text="PASS"')){console.log('preview-client-text-browser.test.js: PASS '+executable+' version='+version+' elements='+(dom.match(/class="canvas-element\b/g)||[]).length);return;}
 }throw Error(JSON.stringify(attempts));
}
run().catch(e=>{console.error(e);process.exitCode=1;});
