const assert = require('node:assert/strict');
const {parse} = require('./preview-inputs-integration.test');
const slider = '<Slider|wil=NewopUI|pcbgimg=298|pcbarimg=299|pcballimg=297|sliderid=N0|x=60|y=120|width=400|height=20|maxvalue=100|defvalue=25>';
const source = '[@main]\n#SAY\n<Text|text=姓名=$STM(USERNAME) 等级=$STM(LEVEL) 数量=$STM(ITEMCOUNT_木剑) 金币=$STM(MONEY_1,2)|x=60|y=50>\n<Text|text=滑块=$STM(SLIDERV_N0)|x=60|y=85>\n'+slider;
function run() {
 const menuSource=source+'\n<MenuItem|menuid=S0|x=60|y=200|width=240|height=30|itemname=姓名=$STM(USERNAME)#血量=$STM(HP)#滑块=$STM(SLIDERV_N0)|select=姓名=$STM(USERNAME)|itemhei=30>';
 const menu=parse(menuSource,{},'996PC').pages[0].elements.at(-1).menuPreview;
 assert.deepEqual(menu.clientDisplay?.items.map(line=>line.map(r=>r.text).join('')),['姓名=预览文字','血量=0','滑块=25']);
 assert.deepEqual(menu.items,['姓名=$STM(USERNAME)','血量=$STM(HP)','滑块=$STM(SLIDERV_N0)'],'display must not rewrite menu identities');
 const menuSet=parse(menuSource,{'STM(USERNAME)':'#<Img|pcimg=12>/$STM(HP)'},'996PC').pages[0].elements.at(-1).menuPreview;
 assert.equal(menuSet.clientDisplay.items[0].map(r=>r.text).join(''),'姓名=#<Img|pcimg=12>/$STM(HP)');
 assert.equal(menuSet.items.length,3);
 const menuEmpty=parse(menuSource.replace('select=姓名=$STM(USERNAME)','select=$STM(USERNAME)'),{'STM(USERNAME)':''},'996PC').pages[0].elements.at(-1).menuPreview;
 assert.equal(menuEmpty.clientDisplay.selected.map(r=>r.text).join(''),'','custom default label preserves explicit empty');
 const menuLiteral=parse('[@main]\n#SAY\n<MenuItem|menuid=S0|x=20|y=20|itemname=<$STR(S1)>|select=<$STR(S1)>>',{S1:'$STM(HP)'},'996PC');
 assert.ok(!menuLiteral.previewInputs.some(i=>i.name==='STM(HP)'),'user literal menu text must not become client expression');
 const tipSource=source.replace('text=姓名=', 'tips=姓名=$STM(USERNAME) 血量=$STM(HP) 滑块=$STM(SLIDERV_N0)|text=姓名=');
 const tip=parse(tipSource,{},'996PC').pages[0].elements[0].tooltipPreview;
 assert.equal(tip.lines.flat().map(r=>r.text).join(''),'姓名=预览文字 血量=0 滑块=25');
 const tipSet=parse(tipSource,{'STM(USERNAME)':'<$STR(S0)>/$STM(HP)','STM(HP)':'123'},'996PC');
 assert.equal(tipSet.pages[0].elements[0].tooltipPreview.lines.flat().map(r=>r.text).join(''),'姓名=<$STR(S0)>/$STM(HP) 血量=123 滑块=25');
 assert.equal(tipSet.pages[0].elements[0].tooltipPreview.raw,tip.raw,'tooltip source must stay unchanged');
 const onlyTip='[@main]\n#SAY\n<Img|wil=NewopUI|pcimg=12|x=20|y=20|tips={姓名=$STM(USERNAME)/FCOLOR=250} 血量=$STM(HP)|tipsx=8|tipsy=9>';
 const imageTip=parse(onlyTip,{},'996PC').pages[0].elements[0];
 assert.equal(imageTip.tooltipPreview.lines.flat().map(r=>r.text).join(''),'姓名=预览文字 血量=0');
 assert.ok(imageTip.tooltipPreview.lines.flat().some(r=>r.color));
 assert.equal(imageTip.tooltipPreview.offsetX,8);assert.equal(imageTip.tooltipPreview.offsetY,9);
 assert.equal(imageTip.assetRef?.imageIndex,12);
 const emptyTip=parse(onlyTip,{'STM(USERNAME)':''},'996PC').pages[0].elements[0];
 assert.equal(emptyTip.tooltipPreview.lines.flat().map(r=>r.text).join(''),'姓名= 血量=0');
 const literalTip=parse(onlyTip.replace('{姓名=$STM(USERNAME)/FCOLOR=250} 血量=$STM(HP)','<$STR(S0)>'),{S0:'$STM(HP)'},'996PC');
 assert.equal(literalTip.pages[0].elements[0].tooltipPreview.lines.flat().map(r=>r.text).join(''),'$STM(HP)');
 assert.ok(!literalTip.previewInputs.some(i=>i.name==='STM(HP)'));
 const model=parse(source,{},'996PC'), elements=model.pages[0].elements;
 assert.equal(elements[0].text,'姓名=预览文字 等级=0 数量=0 金币=0');
 assert.equal(elements[1].text,'滑块=25');
 assert.equal(model.previewInputs.find(i=>i.name==='STM(LEVEL)').kind,'number');
 const set=parse(source,{'STM(USERNAME)':'勇士','STM(LEVEL)':'42','STM(SLIDERV_N0)':'77'},'996PC');
 assert.equal(set.pages[0].elements[1].text,'滑块=77');
 assert.ok(set.pages[0].elements[0].text.includes('姓名=勇士 等级=42'));
 assert.equal(parse(source+'\n'+slider,{},'996PC').pages[0].elements[1].text,'滑块=0','duplicate slider must not bind');
 assert.equal(parse(source.replace('defvalue=25','defvalue=<$STR(N2)>'),{},'996PC').pages[0].elements[1].text,'滑块=0','unknown slider must not borrow zero as evidence');
 for(const engine of ['GOM','GEE']) assert.equal(parse('[@main]\n#SAY\n<TEXT:$STM(LEVEL):20:20>',{},engine).pages[0].elements[0].text,'$STM(LEVEL)');
 const literal=parse('[@main]\n#SAY\n<Text|text=<$STR(S0)>|x=20|y=20>',{S0:'$STM(HP)'},'996PC');
 assert.equal(literal.pages[0].elements[0].text,'$STM(HP)');
 assert.ok(!literal.previewInputs.some(i=>i.name==='STM(HP)'));
 const authored=parse('[@main]\n#ACT\nMOV S0 <Text|text=$STM(HP)|x=20|y=20>\n#SAY\n<$STR(S0)>',{},'996PC');
 assert.equal(authored.pages[0].elements[0].text,'0','source-authored markup still expands');
 const attack='<Img|img=12|x=1|y=1>/$STM(HP)';
 const attacked=parse(source,{'STM(USERNAME)':attack},'996PC');
 assert.equal(attacked.pages[0].elements.length,3);assert.ok(attacked.pages[0].elements[0].text.includes(attack));
 const isolated=parse('[@main]\n#IF\nEQUAL N0 77\n#SAY\n<Text|text=yes|x=1|y=1>\n#ELSESAY\n<Text|text=$STM(SLIDERV_N0)|x=1|y=1>',{'STM(SLIDERV_N0)':'77'},'996PC');
 assert.equal(isolated.conditionGroups[0].satisfied,false);
 const resource=parse('[@main]\n#SAY\n<Img|img=$STM(LEVEL)|x=$STM(LEVEL)|y=20>\n<Text|text=$STM(LEVEL)|x=20|y=20>',{'STM(LEVEL)':'42'},'996PC');
 assert.equal(resource.pages[0].elements[0].assetRef,undefined);
 assert.notEqual(resource.pages[0].elements[0].x,42);
 const pages=parse('[@main]\n#SAY\n<Text|text=$STM(SLIDERV_N0)|x=20|y=20>\n<下一页/@next>\n[@next]\n#SAY\n'+slider,{},'996PC');
 assert.equal(pages.pages[0].elements[0].text,'0','other-page slider is not borrowed');
 const custom=parse(source.replaceAll('N0','N$amount'),{},'996PC');
 assert.equal(custom.pages[0].elements[1].text,'滑块=25');
 assert.equal(parse(source.replaceAll('N0','N$amount').replace('SLIDERV_N$amount','SLIDERV_N$Amount'),{},'996PC').pages[0].elements[1].text,'滑块=0','custom variable suffix is case-sensitive');
 const duplicate=parse(source+'\n'+slider.replace('defvalue=25','defvalue=<$STR(N2)>'),{},'996PC');
 assert.equal(duplicate.pages[0].elements[1].text,'滑块=0','invalid peer still occupies the ID');
 const simplified=parse('[@main]\n#SAY\n<Text|text=$STM(LEVEL)|simplenum=1|x=20|y=20>',{'STM(LEVEL)':'12345'},'996PC').pages[0].elements[0];
 assert.equal(simplified.text,'1.23万');assert.equal(simplified.textPreview.simplifyNumberApproximate,true);
 const scoped=parse('[@main]\n#ACT\nMOV N0 99\n#SAY\n<Text|text=$STM(SLIDERV_N0)|x=20|y=20>\n'+slider,{},'996PC');
 assert.equal(scoped.pages[0].elements[0].text,'25','underlying server variable does not supply client state');
 const empty=parse(source,{'STM(USERNAME)':'','STM(LEVEL)':'0','STM(SLIDERV_N0)':'0'},'996PC');
 assert.ok(empty.pages[0].elements[0].text.startsWith('姓名= 等级=0'));assert.equal(empty.pages[0].elements[1].text,'滑块=0');
 assert.equal(parse(source.replace('text=滑块=$STM(SLIDERV_N0)','text=$STM(WEAPON) $STM(ARMRINGR) $STM(UNPROVED)'),{},'996PC').pages[0].elements[1].text,'预览文字 预览文字 预览文字');
 console.log('preview-client-text.test.js: PASS');
}
if(require.main===module)run();module.exports={source,slider,run};
