const assert = require('node:assert/strict');
const path = require('node:path');
const runtimeRoot = path.resolve(process.env.BOO_NPC_DIALOG_RUNTIME_ROOT || path.join(__dirname, '..'));
const { executePreviewScopedVariableCommand: execute } = require(path.join(runtimeRoot, 'out/ui-dialog/preview-scoped-variables'));

function run() {
  const state = new Map();
  const writes = [];
  const read = name => state.get(name);
  const write = (name, value, deps) => { writes.push({ name, value, deps }); value === undefined ? state.delete(name) : state.set(name, value); };
  const command = (name, rest, engine = 'GOM', type = 'number') => execute(name, rest, read, write, engine, () => type);
  assert.equal(command('VAR', 'Integer HUMAN 次数'), true);
  assert.equal(read('HUMAN(次数)'), '0');
  state.set('HUMAN(次数)', '9007199254740993');
  command('VAR', 'Integer HUMAN 次数');
  assert.equal(read('HUMAN(次数)'), '9007199254740993', 'declaration preserves chosen initial value');
  command('CALCVAR', 'HUMAN 次数 + 2');
  assert.equal(read('HUMAN(次数)'), '9007199254740995');
  state.set('N0', '3');
  command('CALCVAR', 'HUMAN 次数 - <$STR(N0)>');
  assert.equal(read('HUMAN(次数)'), '9007199254740992');
  assert.ok(writes.at(-1).deps.includes('N0') && writes.at(-1).deps.includes('HUMAN(次数)'));
  const count = writes.length;
  assert.equal(command('SAVEVAR', 'HUMAN 次数 D:/do-not-create.txt'), true);
  assert.equal(writes.length, count, 'SAVEVAR is completely non-mutating');
  assert.equal(command('LOADVAR', 'HUMAN 次数 D:/do-not-read.txt'), true);
  assert.equal(read('HUMAN(次数)'), undefined, 'LOADVAR must invalidate stale source values');
  assert.equal(command('VAR', 'Integer GUILD 次数', 'GOM'), false, 'no GOM scope borrowing');
  assert.equal(command('VAR', 'Integer GUILD 次数', 'GEE'), true);
  assert.equal(command('CALCVAR', 'GUILD 次数 = 100', 'GEE'), true);
  assert.equal(read('GUILD(次数)'), '100');
  assert.equal(command('VAR', 'String GLOBAL 名称', '996PC', 'text'), true);
  assert.equal(command('CALCVAR', 'GLOBAL 名称 = "文字 : | /@示例"', '996PC', 'text'), true);
  assert.equal(read('GLOBAL(名称)'), '文字 : | /@示例');
  assert.equal(command('VAR', 'Integer HUMAN 合区 4', '996PC'), true);
  assert.equal(read('HUMAN(合区)'), '0', 'fourth argument is merge mode, not initial value');
  command('CALCVAR', 'HUMAN 合区 = 12', '996PC');
  command('CALCVAR', 'HUMAN 合区 * 3', '996PC');
  command('CALCVAR', 'HUMAN 合区 / 9', '996PC');
  assert.equal(read('HUMAN(合区)'), '4');
  command('CALCVAR', 'HUMAN 合区 / 3', '996PC');
  assert.equal(read('HUMAN(合区)'), undefined, 'unevidenced rounding is unknown');
  state.set('HUMAN(合区)', '4');
  command('CALCVAR', 'HUMAN 合区 / 0', '996PC');
  assert.equal(read('HUMAN(合区)'), undefined);
  state.set('HUMAN(合区)', '4');
  command('CALCVAR', 'HUMAN 合区 = <$PLUGIN_UNKNOWN>', '996PC');
  assert.equal(read('HUMAN(合区)'), undefined);
  assert.equal(command('VAR', 'Integer CHUMAN 次数'), false, 'current-object scope is display-only');
  assert.equal(command('GETVAR', 'HUMAN 次数 N0'), false);
  assert.equal(command('SETVAR', 'HUMAN 次数 1'), false);
  console.log('preview-scoped-variables.test.js: PASS (source order, integer precision, engine isolation, I/O safety)');
}
if (require.main === module) run();
module.exports = { run };
