const assert = require('node:assert/strict');
const path = require('node:path');
const runtimeRoot = path.resolve(process.env.BOO_NPC_DIALOG_RUNTIME_ROOT || path.join(__dirname, '..'));
const { normalizePreviewCollectionValue: normalize, previewCollectionKind: kind,
  resolvePreviewCollectionExpression: resolve, evaluatePreviewCollectionCondition: condition,
  applyPreviewCollectionCommand: apply } = require(path.join(runtimeRoot, 'out/ui-dialog/preview-collections'));

function state(seed = {}, engine = 'GOM') {
  const values = new Map(Object.entries(seed));
  const writes = [];
  const read = name => values.get(name);
  return { values, writes, read, get: name => values.get(name),
    run(command, rest) { return apply(command, rest, read, (name, value, dependencies) => { writes.push({ name, value, dependencies }); values.set(name, value); }, engine); },
    resolve(expression) { return resolve(expression, read, engine); },
    check(command, rest) { return condition(command, rest, read, engine); } };
}

function run() {
  assert.equal(normalize('list', '["甲",2,"9007199254740993"]'), '["甲","2","9007199254740993"]');
  assert.equal(normalize('list', '[9007199254740993,1.0000000000000000001]'), '["9007199254740993","1.0000000000000000001"]', 'JSON numeric lexemes must not silently round');
  assert.equal(normalize('list', '[1e4000]'), undefined);
  assert.equal(normalize('list', '[true]'), undefined);
  assert.equal(normalize('list', '[null]'), undefined);
  assert.equal(normalize('list', '[{}]'), undefined);
  assert.equal(normalize('list', '["a\\nb"]'), undefined);
  assert.equal(normalize('dictionary', '{"a":{"nested":1}}'), undefined);
  assert.equal(normalize('dictionary', '{"":1}'), undefined);
  assert.equal(normalize('dictionary', '{"__proto__":"safe","constructor":2}'), '{"__proto__":"safe","constructor":"2"}');
  assert.equal(normalize('list', '["a",["b","c"]]'), '["a","[b,c]"]');
  assert.equal(normalize('list', JSON.stringify(Array(513).fill('a'))), undefined);
  assert.equal(normalize('list', JSON.stringify(['a'.repeat(4097)])), undefined);
  assert.equal(normalize('list', JSON.stringify(Array(512).fill('a'.repeat(512)))), undefined);
  assert.equal(normalize('list', `${'['.repeat(2000)}0${']'.repeat(2000)}`), undefined, 'depth bounded before recursive normalization');
  assert.equal(kind('l$大小写', '996PC'), 'list');
  assert.equal(kind('GL$List', 'GOM'), 'list');
  assert.equal(kind('GL$List', 'GEE'), undefined);
  assert.equal(kind('D$Dict', '996PC'), undefined);

  const s = state({ 'L$名单': '["张三","李四","张三"]', 'D$积分': '{"张三":"100","李四":"200"}', N0: '1', 'S$键': '李四' });
  assert.equal(s.resolve('<$STR(L$名单[0])>'), '张三');
  assert.equal(s.resolve('L$名单[-1]'), '张三');
  assert.equal(s.resolve('L$名单[<$STR(N0)>]'), '李四');
  assert.equal(s.resolve('<$STR(D$积分[<$STR(S$键)>])>'), '200');
  assert.equal(s.resolve('D$积分[不存在]'), '');
  assert.equal(s.resolve('D$积分[toString]'), '');
  assert.equal(s.resolve('D$积分'), '{张三:100,李四:200}');
  assert.equal(s.resolve('L$名单'), '[张三,李四,张三]');
  assert.equal(s.resolve('L$名单[100]'), undefined);
  assert.equal(s.resolve('L$名单[1.5]'), undefined);
  assert.equal(s.resolve('L$名单[<$STR(N99)>]'), undefined);
  s.values.set('S$字面量', 'U101');
  s.values.set('U101', 'should-not-be-read');
  s.run('ADDTOLIST', 'L$名单 <$STR(S$字面量)>');
  assert.equal(s.resolve('L$名单[-1]'), 'U101', 'template result is data, not another variable');
  s.run('REMOVELISTBYINDEX', 'L$名单 -1');
  s.values.set('S$字面量', '"quoted"');
  s.run('ADDTOLIST', 'L$名单 <$STR(S$字面量)>');
  assert.equal(s.resolve('L$名单[-1]'), '"quoted"', 'template result quotes remain literal');
  s.run('REMOVELISTBYINDEX', 'L$名单 -1');
  assert.equal(s.check('CHECKVARINLIST', 'L$名单 张三'), true);
  assert.equal(s.check('CHECKINDICT', 'D$积分 李四 0'), true);
  assert.equal(s.check('CHECKINDICT', 'D$积分 200 1'), true);
  assert.equal(s.check('CHECKINDICT', 'D$积分 200 2'), undefined);
  assert.equal(s.check('CHECKDICTALLDIGIT', 'D$积分'), true);
  assert.equal(s.check('CHECKLISTALLDIGIT', 'L$名单'), false);
  assert.equal(s.run('MOV', 'L$测试 [11,22,33,aa]'), true);
  assert.equal(s.get('L$测试'), '["11","22","33","aa"]');
  assert.deepEqual(s.writes.at(-1).dependencies, [], 'whole source assignment must not inherit old target preview origin');
  s.run('MOV', 'L$测试[<$STR(N0)>] 00');
  assert.equal(s.get('L$测试'), '["11","00","33","aa"]');
  assert.ok(s.writes.at(-1).dependencies.includes('N0'));
  s.run('INC', 'L$测试[0] abc');
  assert.equal(s.resolve('L$测试[0]'), '11abc');
  s.run('DEC', 'L$测试[0] abc');
  assert.equal(s.resolve('L$测试[0]'), '11');
  s.run('MOV', 'L$测试[0] <$STR(L$名单)>');
  assert.equal(s.resolve('L$测试[0]'), '[张三,李四,张三]');
  s.run('MOV', 'D$字典 {张三:100,李四:200}');
  s.run('MOV', 'D$字典[周八] 600');
  s.run('INC', 'D$字典 赵六:400');
  s.run('DEC', 'D$字典 李四');
  assert.equal(s.resolve('D$字典'), '{张三:100,周八:600,赵六:400}');
  s.run('MOV', 'D$字典[__proto__] harmless');
  assert.equal(s.resolve('D$字典[__proto__]'), 'harmless');
  assert.equal({}.harmless, undefined);
  s.run('GETDICTKEYCOUNT', 'D$字典 N1');
  assert.equal(s.get('N1'), '4');
  s.run('GETDICTITEMS', 'D$字典 0 L$键');
  assert.equal(s.resolve('L$键[0]'), '张三');
  s.run('GETDICTMAXVALUE', 'D$积分 S$冠军 N$最高');
  assert.equal(s.get('S$冠军'), '李四');
  assert.equal(s.get('N$最高'), '200');
  s.run('MOV', 'D$积分[李四] 100');
  s.run('GETDICTMAXVALUE', 'D$积分 S$冠军 N$最高');
  assert.equal(s.get('S$冠军'), undefined, 'tied unspecified winner must not be invented');
  assert.equal(s.get('N$最高'), '100');
  s.run('GETLISTVARCOUNT', 'L$名单 N$数量');
  assert.equal(s.get('N$数量'), '3');
  s.run('GETLISTVARINDEX', 'L$名单 李四 N$位置');
  assert.equal(s.get('N$位置'), '1');
  s.run('JOINLIST', 'L$名单 S$合并 、');
  assert.equal(s.get('S$合并'), '张三、李四、张三');
  s.run('SPLITTOLIST', '<$STR(S$合并)> 、 L$拆分');
  assert.equal(s.get('L$拆分'), s.get('L$名单'));
  s.run('COUNTINLIST', 'L$名单 张三 N$次数');
  assert.equal(s.get('N$次数'), '2');
  s.run('UNIQUELIST', 'L$名单 L$去重');
  assert.equal(s.get('L$去重'), '["张三","李四"]');
  s.run('CLONELIST', 'L$去重 L$复制');
  s.run('CONCATLIST', 'L$复制 L$去重 L$连接');
  assert.equal(s.get('L$连接'), '["张三","李四","张三","李四"]');
  s.run('DEC', 'L$连接 张三');
  assert.equal(s.get('L$连接'), '["李四","张三","李四"]');
  s.run('REMOVELISTBYCONTENT', 'L$连接 李四');
  assert.equal(s.get('L$连接'), '["张三"]');
  s.run('ADDTOLIST', 'L$连接 新人');
  s.run('INSERTTOLIST', 'L$连接 前面 0');
  s.run('REPLACELISTBYINDEX', 'L$连接 替换 1');
  assert.equal(s.get('L$连接'), '["前面","替换","新人"]');
  s.run('REMOVELISTBYINDEX', 'L$连接 -1');
  s.run('REVERSELIST', 'L$连接 L$反转');
  assert.equal(s.get('L$反转'), '["替换","前面"]');
  s.run('MOV', 'L$数字 [9007199254740993,9007199254740992,0.02,-0.01]');
  s.run('GETLISTMAXVAR', 'L$数字 N$最大');
  assert.equal(s.get('N$最大'), '9007199254740993');
  s.run('GETLISTMINVAR', 'L$数字 N$最小');
  assert.equal(s.get('N$最小'), '-0.01');
  s.run('SORTLIST', 'L$数字 L$排序 0 0');
  assert.equal(s.get('L$排序'), '["-0.01","0.02","9007199254740992","9007199254740993"]');
  s.run('SUMLIST', 'L$数字 N$总和');
  assert.equal(s.get('N$总和'), '18014398509481985.01');
  s.run('MOV', 'L$精度 [1.0000000000000000001,1.0000000000000000002]');
  s.run('SUMLIST', 'L$精度 N$精度');
  assert.equal(s.get('N$精度'), '2.0000000000000000003');
  s.run('EXTRACTLIST', 'L$排序 L$切片 -1 -3 2');
  assert.equal(s.get('L$切片'), '["9007199254740993","0.02"]');
  s.run('EXTRACTLIST', 'L$排序 S$切片 0 2');
  assert.equal(s.get('S$切片'), '[-0.01,0.02,9007199254740992]');
  s.run('MOV', 'L$排行 [a_30,b_10,c_20]');
  s.run('SORTLIST', 'L$排行 L$排行 0 0 _ 2');
  assert.equal(s.get('L$排行'), '["b_10","c_20","a_30"]');
  s.run('MOV', 'L$重复 [a,a,A]');
  s.run('REPLACELISTBYCONTENT', 'L$重复 a b 1');
  assert.equal(s.get('L$重复'), '["b","a","A"]');
  s.run('RANDOMPICKLIST', 'L$名单 S$随机');
  assert.equal(s.get('S$随机'), undefined);
  s.run('SHUFFLELIST', 'L$名单 L$乱序');
  assert.equal(s.get('L$乱序'), undefined);
  assert.equal(s.run('GLOBALLISTSAVEFILE', 'secret.txt'), false, 'no filesystem persistence');
  assert.equal(s.run('GOTO', '@server'), false, 'no server calls');
  s.run('MOV', 'L$名单');
  assert.equal(s.resolve('L$名单'), '');
  s.run('MOV', 'L$名单 []');
  assert.equal(s.resolve('L$名单'), '[]');
  s.run('MOV', 'L$名单 not-a-list');
  assert.equal(s.get('L$名单'), undefined, 'invalid writes must invalidate stale data');
  const invalid = state({ 'L$输入': '["known"]', 'L$旧': '["stale"]', N$旧: '935', 'D$输入': '{"name":"x"}' });
  invalid.run('REVERSELIST', 'L$输入 L$旧 unexpected');
  assert.equal(invalid.get('L$旧'), undefined, 'invalid arity does not retain stale output');
  invalid.run('GETLISTVARCOUNT', 'L$不存在 N$旧');
  assert.equal(invalid.get('N$旧'), undefined, 'unresolved source clears output and its privileged origin');
  invalid.run('MOV', 'L$输入[99] x');
  assert.equal(invalid.get('L$输入'), undefined, 'out-of-bounds mutation cannot keep old values');
  invalid.run('GETDICTMAXVALUE', 'D$输入 S$旧 N$旧');
  assert.equal(invalid.get('S$旧'), undefined);
  assert.equal(invalid.get('N$旧'), undefined);

  const gee = state({ 'L$重复': '["a","a","A"]', 'GL$禁止': '["x"]' }, 'GEE');
  gee.run('REPLACELISTBYCONTENT', 'L$重复 a b 1');
  assert.equal(gee.get('L$重复'), '["b","b","A"]', 'GEE fourth field is case-sensitive mode, not GOM count');
  assert.equal(gee.run('JOINLIST', 'L$重复 S$文本 ,'), false);
  assert.equal(gee.resolve('GL$禁止[0]'), undefined);
  assert.equal(gee.resolve('L$重复[-1]'), 'A');
  const pc = state({ 'L$数组': '["a","b"]', 'D$字典': '{"a":"1"}' }, '996PC');
  assert.equal(pc.resolve('L$数组[0]'), 'a');
  assert.equal(pc.resolve('L$数组[-1]'), undefined);
  assert.equal(pc.resolve('D$字典[a]'), undefined);
  assert.equal(pc.check('CHECKINDICT', 'D$字典 a'), undefined);
  pc.run('INSERTTOLIST', 'L$数组 x -1');
  assert.equal(pc.get('L$数组'), '["a","x","b"]');
  console.log('preview-collections.test.js: PASS');
}
if (require.main === module) run();
module.exports = { run };
